// -----------------------------------------------------------------------------
// <auto-generated />
// VS.Helper global imports.
// Keeps legacy command files clean while ensuring common .NET types are available
// in every source file after SDK/VSIX merge passes.
// -----------------------------------------------------------------------------

global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
