// VSCommandTable.cs
// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated/synchronized for VS.Helper.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VS.Helper
{
    using System;

    internal sealed partial class PackageGuids
    {
        public const string VSExtensionString = "32bf848a-bd7e-4f10-9b06-9c9f9feb8e4a";
        public static Guid VSHelper = new Guid(VSExtensionString);
    }

    internal sealed partial class PackageIds
    {
        public const int VSHelperGroup = 0x0001;
        public const int BuildZipCommand = 0x0200;
        public const int CreateZipConfigCommand = 0x0300;
        public const int CommitStampSyncGitCommand = 0x0400;
        public const int BuildSolutionCommand = 0x0450;
        public const int RunSwarmCommand = 0x0460;
        public const int EvolveSwarmCommand = 0x0470;
        public const int SelfUpgradeCommand = 0x0480;
        public const int VSHelperToolsCommand = 0x0500;
    }
}
