// source.extension.cs
// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VS.Helper
{
    internal sealed partial class Vsix
    {
        public const string Id = "VS.Helper.594f3931-1da9-4fe1-83cf-803dab09a528";
        public const string Name = "VS.Helper";
        public const string Description = @"VS Project помощник.";
        public const string Language = "ru-RU";
        public const string Version = "2026.2.1.59";
        public const string Author = "GH-Programmer";
        public const string Tags = "";
        public const bool IsPreview = true;
    }
}
